<?php
    function support_contact_form_alter(&$form, &$form_state, $form_id) {
        if ($form_id == 'contact_site_form') {
            $form['copy']['#access'] = 0;
        }
    }

    function support_contact_follow_networks_alter(&$networks, $uid = 0){
        $networks[$uid]['imdb'] = array(
          'title' => t('IMDB'),
          'domain' => 'imdb.com',
        );

        $networks[$uid]['drupal'] = array(
          'title' => t('Drupal.org'),
          'domain' => 'drupal.org',
        );
    }
